networks:
  app-network:
    driver: bridge

services:

  db:
    image: postgres:16
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - app-network
    ports:
      - "5050:5050"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PG_USERNAME=${PG_USERNAME:-test} # Creates an environment variable of value "test" editable in Coolify's UI
      - PG_HASHED_PASSWORD=${PG_HASHED_PASSWORD:-$2y$12$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG} # test. CHANGE THIS!
    labels:
      # Basic auth for pgadmin using the environment variables PG_USERNAME and PG_HASHED_PASSWORD
      - traefik.http.middlewares.mybasicauth.basicauth.users=${PG_USERNAME?Variable not set}:${PG_HASHED_PASSWORD?Variable not set}

  backend:
    restart: always
    networks:
      - app-network
    ports:
      - "9000:80"
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: false

volumes:
  postgres_data:
  pgadmin-data: