networks:
  app-network:
    driver: bridge

services:

  db:
    image: postgres:16
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - app-network
    ports:
      - "5050:5050"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    restart: always
    networks:
      - app-network
    ports:
      - "8888:80"
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: false

volumes:
  postgres_data:
  pgadmin-data: